# Generated by Django 4.2.7 on 2023-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_deadline_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_after_deadline",
            field=models.BooleanField(default=False),
        ),
    ]
