# Generated by Django 4.2.7 on 2023-11-23 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_task_completed_after_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_after_deadline",
        ),
    ]
